default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_gourmet_dev

test:
  <<: *default
  database: pai_gourmet_test

production:
  <<: *default
  database: pai_gourmet_production
  username: pai_gourmet
  password: <%= ENV["PAI_GOURMET_DATABASE_PASSWORD"] %>
